namespace MaceEvolve.Core.Enums
{
    public enum CreatureInput
    {
        PercentMaxEnergy,
        FoodToLeftPercentMaxEnergy,
        FoodToLeftPercentMaxNutrients,
        FoodToRightPercentMaxEnergy,
        FoodToRightPercentMaxNutrients,
        FoodToFrontPercentMaxEnergy,
        FoodToFrontPercentMaxNutrients,
        FoodToBackPercentMaxEnergy,
        FoodToBackPercentMaxNutrients,
        DistanceFromTopWorldBound,
        DistanceFromLeftWorldBound,
        RandomInput,
        PercentNutrientsRequiredToReproduce,
        PercentEnergyRequiredToReproduce,
        PercentMaxAge,
        PercentMaxHealth,
        WillNaturallyHeal,
        PercentMassRequiredToReproduce,
        VisibleAreaCreatureDensity,
        VisibleAreaFoodDensity,
        AngleToClosestVisibleCreature,
        AngleToClosestVisibleFood,
        ProximityToClosestVisibleCreature,
        ProximityToClosestVisibleFood
    }
}
